batch_size: -1
dataset: camera
lr: 0.001
lr_decay: 1.
device: cuda
filters: 
  - fourier
  - gabor
  - siren_like
network_specs: 
-
  - 1
  - 256
-
  - 1
  - 512
-
  - 4
  - 256
input_scale: 256.
f_solver: fixed_point_iter
f_max_iter: 100
grad: 3
no_skip_solver: false
max_train_iters: 5000
log_freq: 50
verbose: false
continue_run: false

