GPUS: (0,1)
LOG_DIR: 'log/'
DATA_DIR: ''
WORKERS: 4
PRINT_FREQ: 100

MODEL: 
  NAME: mdeq
  NUM_LAYERS: 10
  NUM_CLASSES: 10
  NUM_GROUPS: 8
  DOWNSAMPLE_TIMES: 0
  EXPANSION_FACTOR: 5
  IMAGE_SIZE: 
    - 32
    - 32
  EXTRA:
    FULL_STAGE:
      NUM_MODULES: 1
      NUM_BRANCHES: 4
      BLOCK: BASIC
      HEAD_CHANNELS:
      - 14
      - 28
      - 56
      - 112
      FINAL_CHANSIZE: 1680
      NUM_BLOCKS:
      - 1
      - 1
      - 1
      - 1
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      - 256
      FUSE_METHOD: SUM
CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
DATASET:
  DATASET: 'cifar10'
  DATA_FORMAT: 'jpg'
  ROOT: './data/cifar10'
  TEST_SET: 'val'
  TRAIN_SET: 'train'
  AUGMENT: true
TEST:
  BATCH_SIZE_PER_GPU: 500
  MODEL_FILE: ''
TRAIN:
  BATCH_SIZE_PER_GPU: 64
  BEGIN_EPOCH: 0
  END_EPOCH: 220
  RESUME: false
  LR_SCHEDULER: 'cosine'
  LR_FACTOR: 0.1
  LR_STEP:
  - 30
  - 60
  - 90
  OPTIMIZER: sgd
  LR: 0.1
  WD: 0.0001
  MOMENTUM: 0.9
  NESTEROV: false
  SHUFFLE: true
DEBUG:
  DEBUG: false
